job_1: {varname: ivt, year: '2030'}
job_10: {varname: ivt, year: '2039'}
job_11: {varname: ivt, year: '2040'}
job_12: {varname: ivt, year: '2041'}
job_13: {varname: ivt, year: '2042'}
job_14: {varname: ivt, year: '2043'}
job_15: {varname: ivt, year: '2044'}
job_16: {varname: ivt, year: '2045'}
job_17: {varname: ivt, year: '2046'}
job_18: {varname: ivt, year: '2047'}
job_19: {varname: ivt, year: '2048'}
job_2: {varname: ivt, year: '2031'}
job_20: {varname: ivt, year: '2049'}
job_21: {varname: ivt, year: '2050'}
job_22: {varname: ivt, year: '2051'}
job_23: {varname: ivt, year: '2052'}
job_24: {varname: ivt, year: '2053'}
job_25: {varname: ivt, year: '2054'}
job_26: {varname: ivt, year: '2055'}
job_27: {varname: ivt, year: '2056'}
job_28: {varname: ivt, year: '2057'}
job_29: {varname: ivt, year: '2058'}
job_3: {varname: ivt, year: '2032'}
job_30: {varname: ivt, year: '2059'}
job_31: {varname: ivt, year: '2060'}
job_4: {varname: ivt, year: '2033'}
job_5: {varname: ivt, year: '2034'}
job_6: {varname: ivt, year: '2035'}
job_7: {varname: ivt, year: '2036'}
job_8: {varname: ivt, year: '2037'}
job_9: {varname: ivt, year: '2038'}
