job_1:
  model: gfdl
  varname: ivt
  year: '2030'
job_10:
  model: gfdl
  varname: ivt
  year: '2039'
job_100:
  model: gfdl
  varname: uv925
  year: '2036'
job_101:
  model: gfdl
  varname: uv925
  year: '2037'
job_102:
  model: gfdl
  varname: uv925
  year: '2038'
job_103:
  model: gfdl
  varname: uv925
  year: '2039'
job_104:
  model: gfdl
  varname: uv925
  year: '2040'
job_105:
  model: gfdl
  varname: uv925
  year: '2041'
job_106:
  model: gfdl
  varname: uv925
  year: '2042'
job_107:
  model: gfdl
  varname: uv925
  year: '2043'
job_108:
  model: gfdl
  varname: uv925
  year: '2044'
job_109:
  model: gfdl
  varname: uv925
  year: '2045'
job_11:
  model: gfdl
  varname: ivt
  year: '2040'
job_110:
  model: gfdl
  varname: uv925
  year: '2046'
job_111:
  model: gfdl
  varname: uv925
  year: '2047'
job_112:
  model: gfdl
  varname: uv925
  year: '2048'
job_113:
  model: gfdl
  varname: uv925
  year: '2049'
job_114:
  model: gfdl
  varname: uv925
  year: '2050'
job_115:
  model: gfdl
  varname: uv925
  year: '2051'
job_116:
  model: gfdl
  varname: uv925
  year: '2052'
job_117:
  model: gfdl
  varname: uv925
  year: '2053'
job_118:
  model: gfdl
  varname: uv925
  year: '2054'
job_119:
  model: gfdl
  varname: uv925
  year: '2055'
job_12:
  model: gfdl
  varname: ivt
  year: '2041'
job_120:
  model: gfdl
  varname: uv925
  year: '2056'
job_121:
  model: gfdl
  varname: uv925
  year: '2057'
job_122:
  model: gfdl
  varname: uv925
  year: '2058'
job_123:
  model: gfdl
  varname: uv925
  year: '2059'
job_124:
  model: gfdl
  varname: uv925
  year: '2060'
job_125:
  model: gfdl
  varname: snow
  year: '2030'
job_126:
  model: gfdl
  varname: snow
  year: '2031'
job_127:
  model: gfdl
  varname: snow
  year: '2032'
job_128:
  model: gfdl
  varname: snow
  year: '2033'
job_129:
  model: gfdl
  varname: snow
  year: '2034'
job_13:
  model: gfdl
  varname: ivt
  year: '2042'
job_130:
  model: gfdl
  varname: snow
  year: '2035'
job_131:
  model: gfdl
  varname: snow
  year: '2036'
job_132:
  model: gfdl
  varname: snow
  year: '2037'
job_133:
  model: gfdl
  varname: snow
  year: '2038'
job_134:
  model: gfdl
  varname: snow
  year: '2039'
job_135:
  model: gfdl
  varname: snow
  year: '2040'
job_136:
  model: gfdl
  varname: snow
  year: '2041'
job_137:
  model: gfdl
  varname: snow
  year: '2042'
job_138:
  model: gfdl
  varname: snow
  year: '2043'
job_139:
  model: gfdl
  varname: snow
  year: '2044'
job_14:
  model: gfdl
  varname: ivt
  year: '2043'
job_140:
  model: gfdl
  varname: snow
  year: '2045'
job_141:
  model: gfdl
  varname: snow
  year: '2046'
job_142:
  model: gfdl
  varname: snow
  year: '2047'
job_143:
  model: gfdl
  varname: snow
  year: '2048'
job_144:
  model: gfdl
  varname: snow
  year: '2049'
job_145:
  model: gfdl
  varname: snow
  year: '2050'
job_146:
  model: gfdl
  varname: snow
  year: '2051'
job_147:
  model: gfdl
  varname: snow
  year: '2052'
job_148:
  model: gfdl
  varname: snow
  year: '2053'
job_149:
  model: gfdl
  varname: snow
  year: '2054'
job_15:
  model: gfdl
  varname: ivt
  year: '2044'
job_150:
  model: gfdl
  varname: snow
  year: '2055'
job_151:
  model: gfdl
  varname: snow
  year: '2056'
job_152:
  model: gfdl
  varname: snow
  year: '2057'
job_153:
  model: gfdl
  varname: snow
  year: '2058'
job_154:
  model: gfdl
  varname: snow
  year: '2059'
job_155:
  model: gfdl
  varname: snow
  year: '2060'
job_16:
  model: gfdl
  varname: ivt
  year: '2045'
job_17:
  model: gfdl
  varname: ivt
  year: '2046'
job_18:
  model: gfdl
  varname: ivt
  year: '2047'
job_19:
  model: gfdl
  varname: ivt
  year: '2048'
job_2:
  model: gfdl
  varname: ivt
  year: '2031'
job_20:
  model: gfdl
  varname: ivt
  year: '2049'
job_21:
  model: gfdl
  varname: ivt
  year: '2050'
job_22:
  model: gfdl
  varname: ivt
  year: '2051'
job_23:
  model: gfdl
  varname: ivt
  year: '2052'
job_24:
  model: gfdl
  varname: ivt
  year: '2053'
job_25:
  model: gfdl
  varname: ivt
  year: '2054'
job_26:
  model: gfdl
  varname: ivt
  year: '2055'
job_27:
  model: gfdl
  varname: ivt
  year: '2056'
job_28:
  model: gfdl
  varname: ivt
  year: '2057'
job_29:
  model: gfdl
  varname: ivt
  year: '2058'
job_3:
  model: gfdl
  varname: ivt
  year: '2032'
job_30:
  model: gfdl
  varname: ivt
  year: '2059'
job_31:
  model: gfdl
  varname: ivt
  year: '2060'
job_32:
  model: gfdl
  varname: pcpt
  year: '2030'
job_33:
  model: gfdl
  varname: pcpt
  year: '2031'
job_34:
  model: gfdl
  varname: pcpt
  year: '2032'
job_35:
  model: gfdl
  varname: pcpt
  year: '2033'
job_36:
  model: gfdl
  varname: pcpt
  year: '2034'
job_37:
  model: gfdl
  varname: pcpt
  year: '2035'
job_38:
  model: gfdl
  varname: pcpt
  year: '2036'
job_39:
  model: gfdl
  varname: pcpt
  year: '2037'
job_4:
  model: gfdl
  varname: ivt
  year: '2033'
job_40:
  model: gfdl
  varname: pcpt
  year: '2038'
job_41:
  model: gfdl
  varname: pcpt
  year: '2039'
job_42:
  model: gfdl
  varname: pcpt
  year: '2040'
job_43:
  model: gfdl
  varname: pcpt
  year: '2041'
job_44:
  model: gfdl
  varname: pcpt
  year: '2042'
job_45:
  model: gfdl
  varname: pcpt
  year: '2043'
job_46:
  model: gfdl
  varname: pcpt
  year: '2044'
job_47:
  model: gfdl
  varname: pcpt
  year: '2045'
job_48:
  model: gfdl
  varname: pcpt
  year: '2046'
job_49:
  model: gfdl
  varname: pcpt
  year: '2047'
job_5:
  model: gfdl
  varname: ivt
  year: '2034'
job_50:
  model: gfdl
  varname: pcpt
  year: '2048'
job_51:
  model: gfdl
  varname: pcpt
  year: '2049'
job_52:
  model: gfdl
  varname: pcpt
  year: '2050'
job_53:
  model: gfdl
  varname: pcpt
  year: '2051'
job_54:
  model: gfdl
  varname: pcpt
  year: '2052'
job_55:
  model: gfdl
  varname: pcpt
  year: '2053'
job_56:
  model: gfdl
  varname: pcpt
  year: '2054'
job_57:
  model: gfdl
  varname: pcpt
  year: '2055'
job_58:
  model: gfdl
  varname: pcpt
  year: '2056'
job_59:
  model: gfdl
  varname: pcpt
  year: '2057'
job_6:
  model: gfdl
  varname: ivt
  year: '2035'
job_60:
  model: gfdl
  varname: pcpt
  year: '2058'
job_61:
  model: gfdl
  varname: pcpt
  year: '2059'
job_62:
  model: gfdl
  varname: pcpt
  year: '2060'
job_63:
  model: gfdl
  varname: freezing_level
  year: '2030'
job_64:
  model: gfdl
  varname: freezing_level
  year: '2031'
job_65:
  model: gfdl
  varname: freezing_level
  year: '2032'
job_66:
  model: gfdl
  varname: freezing_level
  year: '2033'
job_67:
  model: gfdl
  varname: freezing_level
  year: '2034'
job_68:
  model: gfdl
  varname: freezing_level
  year: '2035'
job_69:
  model: gfdl
  varname: freezing_level
  year: '2036'
job_7:
  model: gfdl
  varname: ivt
  year: '2036'
job_70:
  model: gfdl
  varname: freezing_level
  year: '2037'
job_71:
  model: gfdl
  varname: freezing_level
  year: '2038'
job_72:
  model: gfdl
  varname: freezing_level
  year: '2039'
job_73:
  model: gfdl
  varname: freezing_level
  year: '2040'
job_74:
  model: gfdl
  varname: freezing_level
  year: '2041'
job_75:
  model: gfdl
  varname: freezing_level
  year: '2042'
job_76:
  model: gfdl
  varname: freezing_level
  year: '2043'
job_77:
  model: gfdl
  varname: freezing_level
  year: '2044'
job_78:
  model: gfdl
  varname: freezing_level
  year: '2045'
job_79:
  model: gfdl
  varname: freezing_level
  year: '2046'
job_8:
  model: gfdl
  varname: ivt
  year: '2037'
job_80:
  model: gfdl
  varname: freezing_level
  year: '2047'
job_81:
  model: gfdl
  varname: freezing_level
  year: '2048'
job_82:
  model: gfdl
  varname: freezing_level
  year: '2049'
job_83:
  model: gfdl
  varname: freezing_level
  year: '2050'
job_84:
  model: gfdl
  varname: freezing_level
  year: '2051'
job_85:
  model: gfdl
  varname: freezing_level
  year: '2052'
job_86:
  model: gfdl
  varname: freezing_level
  year: '2053'
job_87:
  model: gfdl
  varname: freezing_level
  year: '2054'
job_88:
  model: gfdl
  varname: freezing_level
  year: '2055'
job_89:
  model: gfdl
  varname: freezing_level
  year: '2056'
job_9:
  model: gfdl
  varname: ivt
  year: '2038'
job_90:
  model: gfdl
  varname: freezing_level
  year: '2057'
job_91:
  model: gfdl
  varname: freezing_level
  year: '2058'
job_92:
  model: gfdl
  varname: freezing_level
  year: '2059'
job_93:
  model: gfdl
  varname: freezing_level
  year: '2060'
job_94:
  model: gfdl
  varname: uv925
  year: '2030'
job_95:
  model: gfdl
  varname: uv925
  year: '2031'
job_96:
  model: gfdl
  varname: uv925
  year: '2032'
job_97:
  model: gfdl
  varname: uv925
  year: '2033'
job_98:
  model: gfdl
  varname: uv925
  year: '2034'
job_99:
  model: gfdl
  varname: uv925
  year: '2035'
