job_1:
  model: ccsm
  season: DJF
  varname: ivt
job_10:
  model: ccsm
  season: NDJFMA
  varname: pcpt
job_11:
  model: ccsm
  season: DJF
  varname: freezing_level
job_12:
  model: ccsm
  season: MAM
  varname: freezing_level
job_13:
  model: ccsm
  season: JJA
  varname: freezing_level
job_14:
  model: ccsm
  season: SON
  varname: freezing_level
job_15:
  model: ccsm
  season: NDJFMA
  varname: freezing_level
job_16:
  model: ccsm
  season: DJF
  varname: uv925
job_17:
  model: ccsm
  season: MAM
  varname: uv925
job_18:
  model: ccsm
  season: JJA
  varname: uv925
job_19:
  model: ccsm
  season: SON
  varname: uv925
job_2:
  model: ccsm
  season: MAM
  varname: ivt
job_20:
  model: ccsm
  season: NDJFMA
  varname: uv925
job_21:
  model: ccsm
  season: DJF
  varname: snow
job_22:
  model: ccsm
  season: MAM
  varname: snow
job_23:
  model: ccsm
  season: JJA
  varname: snow
job_24:
  model: ccsm
  season: SON
  varname: snow
job_25:
  model: ccsm
  season: NDJFMA
  varname: snow
job_26:
  model: gfdl
  season: DJF
  varname: ivt
job_27:
  model: gfdl
  season: MAM
  varname: ivt
job_28:
  model: gfdl
  season: JJA
  varname: ivt
job_29:
  model: gfdl
  season: SON
  varname: ivt
job_3:
  model: ccsm
  season: JJA
  varname: ivt
job_30:
  model: gfdl
  season: NDJFMA
  varname: ivt
job_31:
  model: gfdl
  season: DJF
  varname: pcpt
job_32:
  model: gfdl
  season: MAM
  varname: pcpt
job_33:
  model: gfdl
  season: JJA
  varname: pcpt
job_34:
  model: gfdl
  season: SON
  varname: pcpt
job_35:
  model: gfdl
  season: NDJFMA
  varname: pcpt
job_36:
  model: gfdl
  season: DJF
  varname: freezing_level
job_37:
  model: gfdl
  season: MAM
  varname: freezing_level
job_38:
  model: gfdl
  season: JJA
  varname: freezing_level
job_39:
  model: gfdl
  season: SON
  varname: freezing_level
job_4:
  model: ccsm
  season: SON
  varname: ivt
job_40:
  model: gfdl
  season: NDJFMA
  varname: freezing_level
job_41:
  model: gfdl
  season: DJF
  varname: uv925
job_42:
  model: gfdl
  season: MAM
  varname: uv925
job_43:
  model: gfdl
  season: JJA
  varname: uv925
job_44:
  model: gfdl
  season: SON
  varname: uv925
job_45:
  model: gfdl
  season: NDJFMA
  varname: uv925
job_46:
  model: gfdl
  season: DJF
  varname: snow
job_47:
  model: gfdl
  season: MAM
  varname: snow
job_48:
  model: gfdl
  season: JJA
  varname: snow
job_49:
  model: gfdl
  season: SON
  varname: snow
job_5:
  model: ccsm
  season: NDJFMA
  varname: ivt
job_50:
  model: gfdl
  season: NDJFMA
  varname: snow
job_51:
  model: cfsr
  season: DJF
  varname: ivt
job_52:
  model: cfsr
  season: MAM
  varname: ivt
job_53:
  model: cfsr
  season: JJA
  varname: ivt
job_54:
  model: cfsr
  season: SON
  varname: ivt
job_55:
  model: cfsr
  season: NDJFMA
  varname: ivt
job_56:
  model: cfsr
  season: DJF
  varname: pcpt
job_57:
  model: cfsr
  season: MAM
  varname: pcpt
job_58:
  model: cfsr
  season: JJA
  varname: pcpt
job_59:
  model: cfsr
  season: SON
  varname: pcpt
job_6:
  model: ccsm
  season: DJF
  varname: pcpt
job_60:
  model: cfsr
  season: NDJFMA
  varname: pcpt
job_61:
  model: cfsr
  season: DJF
  varname: freezing_level
job_62:
  model: cfsr
  season: MAM
  varname: freezing_level
job_63:
  model: cfsr
  season: JJA
  varname: freezing_level
job_64:
  model: cfsr
  season: SON
  varname: freezing_level
job_65:
  model: cfsr
  season: NDJFMA
  varname: freezing_level
job_66:
  model: cfsr
  season: DJF
  varname: uv925
job_67:
  model: cfsr
  season: MAM
  varname: uv925
job_68:
  model: cfsr
  season: JJA
  varname: uv925
job_69:
  model: cfsr
  season: SON
  varname: uv925
job_7:
  model: ccsm
  season: MAM
  varname: pcpt
job_70:
  model: cfsr
  season: NDJFMA
  varname: uv925
job_71:
  model: cfsr
  season: DJF
  varname: snow
job_72:
  model: cfsr
  season: MAM
  varname: snow
job_73:
  model: cfsr
  season: JJA
  varname: snow
job_74:
  model: cfsr
  season: SON
  varname: snow
job_75:
  model: cfsr
  season: NDJFMA
  varname: snow
job_8:
  model: ccsm
  season: JJA
  varname: pcpt
job_9:
  model: ccsm
  season: SON
  varname: pcpt
